const FakeAPI = [
  {
    id: 1,
    image: "images/1.jpg",
    image2: "images/15.jpg",
    image3: "images/8.jpg",
    BHK: "1BHK",
    Area: "290 sqft",
    name: "Sky City",
    category: "Naigaon",
    location: "Naigaon (West)",
    work: "Ready to Move",
    price: "25",
    price2: "30",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences. necessitatibus fugiat in.",
  },
  {
    id: 12,
    image: "images/2.jpg",
    image2: "images/14.jpg",
    image3: "images/7.jpg",
    BHK: "2BHK",
    Area: "320 sqft",
    name: "Blue Heights",
    category: "Naigaon",
    location: "Naigaon (West)",
    work: "Under Construction",
    price: "35",
    price2: "45",
    link: "https://www.youtube.com/watch?v=1Ay23C0HE3I",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 13,
    image: "images/3.jpg",
    image2: "images/13.jpg",
    image3: "images/4.jpg",
    BHK: "3BHK",
    Area: "450 sqft",
    name: "Platinum Avenue",
    category: "Naigaon",
    location: "Naigaon (East)",
    work: "Under Construction",
    price: "55",
    price2: "75",
    link: "https://www.youtube.com/watch?v=2Hm5_-Z43Rg",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 14,
    image: "images/4.jpg",
    image2: "images/12.jpg",
    image3: "images/3.jpg",
    BHK: "2BHK",
    Area: "540 sqft",
    name: "Network Building",
    category: "Naigaon",
    location: "Naigaon (East)",
    work: "Ready to Move",
    price: "30",
    price2: "35",
    link: "https://www.youtube.com/watch?v=fVUvrKwB-zE",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 3,
    image: "images/5.jpg",
    image2: "images/11.jpg",
    image3: "images/9.jpg",
    BHK: "1BHK",
    Area: "310 sqft",
    name: "Surakhsha Smart City",
    category: "Naigaon",
    location: "Naigaon (East)",
    work: "Under Construction",
    price: "24",
    price2: "28",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 11,
    image: "images/6.jpg",
    image2: "images/10.jpg",
    image3: "images/1.jpg",
    BHK: "3BHK",
    Area: "390 sqft",
    name: "Divine Building",
    category: "Naigaon",
    location: "Naigaon (East)",
    work: "Under Construction",
    price: "60",
    price2: "65",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },

  {
    id: 2,
    image: "images/7.jpg",
    image2: "images/9.jpg",
    image3: "images/11.jpg",
    BHK: "1BHK",
    Area: "280 sqft",
    name: "Oasis Building",
    category: "Vasai",
    location: "Vasai (West)",
    work: "Ready to Move",
    price: "26",
    price2: "34",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 5,
    image: "../images/8.jpg",
    image2: "images/1.jpg",
    image3: "images/10.jpg",
    BHK: "2BHK",
    Area: "340 sqft",
    name: "Maratha Palace",
    category: "Vasai",
    location: "Vasai (West)",
    work: "Under Construction",
    price: "36",
    price2: "44",
    link: "https://www.youtube.com/watch?v=1Ay23C0HE3I",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 9,
    image: "../images/9.jpg",
    image2: "images/7.jpg",
    image3: "images/15.jpg",
    BHK: "3BHK",
    Area: "330 sqft",
    name: "Wealth Heights",
    category: "Vasai",
    location: "Vasai (West)",
    work: "Under Construction",
    price: "52",
    price2: "64",
    link: "https://www.youtube.com/watch?v=2Hm5_-Z43Rg",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 10,
    image: "../images/10.jpg",
    image2: "images/6.jpg",
    image3: "images/8.jpg",
    BHK: "2BHK",
    Area: "340 sqft",
    name: "Sky City 215",
    category: "Vasai",
    location: "Vasai (East)",
    work: "Ready to Move",
    price: "32",
    price2: "44",
    link: "https://www.youtube.com/watch?v=fVUvrKwB-zE",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 15,
    image: "../images/11.jpg",
    image2: "images/5.jpg",
    image3: "images/13.jpg",
    BHK: "1BHK",
    Area: "430 sqft",
    name: "Network 210",
    category: "Vasai",
    location: "Vasai (East)",
    work: "Ready to Move",
    price: "22",
    price2: "34",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 16,
    image: "../images/12.jpg",
    image2: "images/4.jpg",
    image3: "images/2.jpg",
    BHK: "3BHK",
    Area: "510 sqft",
    name: "Suraksha Smart City",
    category: "Vasai",
    location: "Vasai (East)",
    work: "Under Construction",
    price: "42",
    price2: "54",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },

  {
    id: 4,
    image: "../images/13.jpg",
    image2: "images/3.jpg",
    image3: "images/9.jpg",
    BHK: "1BHK",
    Area: "292 sqft",
    name: "Maratha Heights",
    category: "Nalasopara",
    location: "Nalasopara (East)",
    work: "Ready to Move",
    price: "30",
    price2: "35",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 8,
    image: "../images/14.jpg",
    image2: "images/2.jpg",
    image3: "images/3.jpg",
    BHK: "2BHK",
    Area: "300 sqft",
    name: "Networtk Heights",
    category: "Nalasopara",
    location: "Nalasopara (East)",
    work: "Under Construction",
    price: "32",
    price2: "54",
    link: "https://www.youtube.com/watch?v=1Ay23C0HE3I",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 8,
    image: "../images/15.jpg",
    image2: "images/1.jpg",
    image3: "images/11.jpg",
    BHK: "3BHK",
    Area: "600 sqft",
    name: "Platinum Heights",
    category: "Nalasopara",
    location: "Nalasopara (East)",
    work: "Ready to Move",
    price: "52",
    price2: "84",
    link: "https://www.youtube.com/watch?v=2Hm5_-Z43Rg",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 8,
    image: "../images/1.jpg",
    image2: "images/15.jpg",
    image3: "images/14.jpg",
    BHK: "1BHK",
    Area: "520 sqft",
    name: "Suraj Heights",
    category: "Nalasopara",
    location: "Nalasopara (West)",
    work: "Under Construction",
    price: "22",
    price2: "34",
    link: "https://www.youtube.com/watch?v=fVUvrKwB-zE",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 8,
    image: "../images/1.jpg",
    image2: "images/14.jpg",
    image3: "images/8.jpg",
    BHK: "3BHK",
    Area: "300 sqft",
    name: "Maratha Tower",
    category: "Nalasopara",
    location: "Nalasopara (West)",
    work: "Ready to Move",
    price: "42",
    price2: "54",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 8,
    image: "../images/3.jpg",
    image2: "images/12.jpg",
    image3: "images/8.jpg",
    BHK: "3BHK",
    Area: "300 sqft",
    name: "Patel Heights",
    category: "Nalasopara",
    location: "Nalasopara (West)",
    work: "Under Construction",
    price: "72",
    price2: "94",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },

  {
    id: 6,
    image: "../images/4.jpg",
    image2: "images/11.jpg",
    image3: "images/6.jpg",
    BHK: "1BHK",
    Area: "290 sqft",
    name: "SS City",
    category: "Virar",
    location: "Virar (East)",
    work: "Ready to Move",
    price: "12",
    price2: "14",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 7,
    image: "../images/5.jpg",
    image2: "images/10.jpg",
    image3: "images/9.jpg",
    BHK: "1BHK",
    Area: "310 sqft",
    name: "Green Tower",
    category: "Virar",
    location: "Virar (East)",
    work: "Under Construction",
    price: "12",
    price2: "14",
    link: "https://www.youtube.com/watch?v=1Ay23C0HE3I",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 7,
    image: "../images/6.jpg",
    image2: "images/11.jpg",
    image3: "images/9.jpg",
    BHK: "2BHK",
    Area: "314 sqft",
    name: "Network Building",
    category: "Virar",
    location: "Virar (East)",
    work: "Ready to Move",
    price: "22",
    price2: "24",
    link: "https://www.youtube.com/watch?v=2Hm5_-Z43Rg",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 7,
    image: "../images/7.jpg",
    image2: "images/9.jpg",
    image3: "images/3.jpg",
    BHK: "2BHK",
    Area: "360 sqft",
    name: "Orange Height",
    category: "Virar",
    location: "Virar (West)",
    work: "Under Construction",
    price: "32",
    price2: "44",
    link: "https://www.youtube.com/watch?v=fVUvrKwB-zE",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 7,
    image: "../images/8.jpg",
    image2: "images/12.jpg",
    image3: "images/1.jpg",
    BHK: "1BHK",
    Area: "300 sqft",
    name: "Sky City",
    category: "Virar",
    location: "Virar (West)",
    work: "Ready to Move",
    price: "12",
    price2: "24",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
  {
    id: 7,
    image: "../images/9.jpg",
    image2: "images/15.jpg",
    image3: "images/8.jpg",
    BHK: "3BHK",
    Area: "420 sqft",
    name: "Platinum Heights",
    category: "Virar",
    location: "Virar (West)",
    work: "Under Construction",
    price: "32",
    price2: "74",
    link: "https://www.youtube.com/watch?v=6K13kPe05Ys&t=165s",
    description:
      "lorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
  },
];

export default FakeAPI;
